sudo: required
language: java
jdk:
  - oraclejdk8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - mysql -u root -e 'CREATE DATABASE testingDatabase;'
  - mysql -u root -e 'CREATE TABLE testingDatabase.airports(id INT(45), name varchar(255), municipality varchar(255),
  type varchar(255));'
  - mysql -u root -e 'insert into testingDatabase.airports values
  ("KAPA", "Centennial Airport" , "Denver", "medium_airport"),
  ("CD06", "Centennial Healthcare Plaza Heliport " , "Englewood", "heliport ");'
  - mysql -u root -e ' select id,name,municipality,type from testingDatabase.airports where name like '%centennial%' or municipality like '%centennial%' order by name;'

script:
  - mvn prepare-package
cache:
  directories:
  - $HOME/.m2
after_script:
  - mv target/site/jacoco/jacoco.xml ./
  - sed -i 's_com/_server/src/main/java/com/_g' jacoco.xml
  - ./cc-test-reporter --debug after-build --exit-code $TRAVIS_TEST_RESULT

addons:
  mariadb: '10.0'

